export const DEFAULT_WORDS_PER_CAPTION = 3;
export const MIN_CAPTION_DURATION_SECONDS = 0.8;

export const MAX_CAPTION_DURATION_SECONDS = 5;
export const MAX_CAPTION_CHARACTERS = 32;
export const CAPTION_PAUSE_GAP_SECONDS = 0.6;
